[build]
    base = "src/"
    command = "echo 'Do Nothing'"

[build.processing.js]
    bundle = true
    minify = true

[build.processing.css]
    bundle = true
    minify = true
[build.processing.html]
    pretty_urls = true
[build.processing.images]
    compress = true

[[plugins]]
    package = "netlify-plugin-js-obfuscator"

    # All inputs are optional, so you can omit this section.
    # Defaults are shown below.
    # You can also refer to `javascript-obfuscator`’s documentation: https://github.com/javascript-obfuscator/javascript-obfuscator.
    [plugins.inputs]
    # Compact code output on one line.
        compact = true
        numbersToExpressions = true
        simplify = true
        shuffleStringArray = true
        splitStrings = true