[build]
base = src/
publish = src/
command = echo "Do Nothing"

[build.processing.js]
    bundle = true
    minify = true

[build.processing.css]
    bundle = true
    minify = true
[build.processing.html]
    pretty_urls = true
[build.processing.images]
    compress = true

[[plugins]]
    package = "netlify-plugin-js-obfuscator"

    # All inputs are optional, so you can omit this section.
    # Defaults are shown below.
    # You can also refer to `javascript-obfuscator`’s documentation: https://github.com/javascript-obfuscator/javascript-obfuscator.
    [plugins.inputs]
    # Compact code output on one line.
        compact = false
    # Enables numbers conversion to expressions
        numbersToExpressions = true
    # Enables additional code obfuscation through simplification.
        simplify = true
    # Randomly shuffles the stringArray array items
        shuffleStringArray = true
    # Splits literal strings into chunks with length of splitStringsChunkLength option value
        splitStrings = true